# Generated by Django 2.2.2 on 2001-12-31 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190623_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2001, 12, 31, 19, 40, 47, 24749, tzinfo=utc)),
        ),
    ]
