# Generated by Django 2.2.2 on 2019-06-24 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20020101_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 24, 7, 42, 58, 522841, tzinfo=utc)),
        ),
    ]
